{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  labels:
    app.kubernetes.io/name: helloworld-ingress
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .path }}
            backend:
              service:
                name: helloworld-service
                port: 
                  number: 80
  {{- end }}
{{ end }}
