apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
